# -*- coding: utf-8 -*-
"""
InvestSkill Institutional Report Integration
============================================
High-speed parser and disk caching engine for InvestSkill institutional
research reports generated by the InvestSkill framework
(https://github.com/yennanliu/InvestSkill).
"""

from __future__ import annotations

import datetime
import json
import logging
import os
import re
from typing import Any, Dict, Optional

from option_quant.config import (
    DATA_DIR,
    INVESTSKILL_OUTPUT_DIR,
    atomic_write_json,
    normalize_symbol,
)

logger = logging.getLogger("option_quant.investskill")


def scan_investskill_reports(
    output_dir: Optional[str] = None,
    max_age_days: int = 7,
    current_date_str: Optional[str] = None,
) -> Dict[str, Dict[str, Any]]:
    """
    Scans the InvestSkill output directory and maps tickers to their latest HTML
    reports, extracting score, verdict, action, and core summary.
    Enforces a strict max_age_days (default 7 days) freshness threshold.
    Optimized with mtime-based JSON disk caching to achieve sub-millisecond lookups.

    Args:
        output_dir: Directory containing InvestSkill HTML reports.
        max_age_days: Maximum days before report is marked as stale.
        current_date_str: Reference date string (YYYY-MM-DD).

    Returns:
        Dictionary mapping normalized ticker symbols to report metadata.
    """
    if output_dir is None:
        output_dir = INVESTSKILL_OUTPUT_DIR

    reports: Dict[str, Dict[str, Any]] = {}
    if not os.path.exists(output_dir):
        return reports

    cache_file = os.path.join(DATA_DIR, "investskill_cache.json")
    disk_cache: Dict[str, Any] = {}
    if os.path.exists(cache_file):
        try:
            with open(cache_file, "r", encoding="utf-8") as fp:
                disk_cache = json.load(fp)
        except Exception:
            disk_cache = {}

    cache_updated = False

    try:
        if current_date_str:
            try:
                curr_d = datetime.datetime.strptime(current_date_str, "%Y-%m-%d").date()
            except Exception:
                curr_d = datetime.date.today()
        else:
            curr_d = datetime.date.today()

        for f in os.listdir(output_dir):
            if f.endswith(".html") and "_report_" in f:
                parts = f.split("_report_")
                raw_t = parts[0].strip()
                date_str = parts[1].replace(".html", "").strip()
                clean_t = normalize_symbol(raw_t).upper()
                filepath = os.path.join(output_dir, f)

                try:
                    r_date = datetime.datetime.strptime(date_str, "%Y-%m-%d").date()
                    age_days = (curr_d - r_date).days
                except Exception:
                    age_days = 0

                is_stale = (age_days > max_age_days)
                mtime = os.path.getmtime(filepath)

                # Check if cached
                if f in disk_cache and disk_cache[f].get("mtime") == mtime:
                    cached_data = disk_cache[f]
                    score = cached_data.get("score")
                    verdict = cached_data.get("verdict", "")
                    action = cached_data.get("action", "")
                    summary = cached_data.get("summary", "")
                else:
                    score = None
                    verdict = ""
                    action = ""
                    summary = ""
                    try:
                        with open(filepath, "r", encoding="utf-8", errors="ignore") as fp:
                            content = fp.read()

                            # 1. Hero Badge / Hero Signal / Hero Meta extraction (Highest priority)
                            hero_sig_m = (
                                re.search(r'class=["\x27][^"\x27]*(?:badge-hero-signal|hero-signal)["\x27][^>]*>([^<]+)</span>', content, re.I) or
                                re.search(r'hero-kpi-lbl[^>]*>\s*(?:多因子综合(?:量化)?评分|综合评分|综合得分|量化评分|Score)[^<]*</div>\s*<div[^>]*class=[\"\x27][^\"\x27]*hero-kpi-val[^\"\x27]*[\"\x27][^>]*>\s*([\d\.\s/]+(?:•|·|\s|&middot;)[^<]+|[\d\.\s/]+)', content, re.I)
                            )
                            if hero_sig_m:
                                raw_badge = hero_sig_m.group(1).strip()
                                if "•" in raw_badge or "·" in raw_badge or "&middot;" in raw_badge:
                                    parts = re.split(r'[•·]|&middot;', raw_badge, maxsplit=1)
                                    p1, p2 = parts[0].strip(), parts[1].strip()
                                    num_m1 = re.search(r'([\d\.]+)\s*(?:/\s*10)?', p1)
                                    num_m2 = re.search(r'([\d\.]+)\s*(?:/\s*10)?', p2)
                                    if num_m1 and not re.search(r'[\u4e00-\u9fa5a-zA-Z]', p1):
                                        score = float(num_m1.group(1))
                                        verdict = p2
                                    elif num_m2:
                                        score = float(num_m2.group(1))
                                        verdict = p1
                                else:
                                    num_m = re.search(r'([\d\.]+)\s*/\s*10', raw_badge)
                                    if num_m:
                                        score = float(num_m.group(1))
                                    else:
                                        verdict = raw_badge

                            # 2. Score regex patterns
                            if score is None:
                                score_m = (
                                    re.search(r"(?:hero-meta-label|signal-lbl|signal-item-label|sb-item-label|hero-kpi-lbl)[^>]*>\s*(?:多因子综合(?:量化)?评分|综合评分|综合得分|量化评分|加权综合量化总分|Score|Composite)[^<]*</(?:span|div|th|td)>\s*<(?:span|div|td)[^>]*class=[\"\x27][^\"\x27]*(?:hero-meta-value|signal-val|signal-item-val|sb-item-val|hero-kpi-val)[^\"\x27]*[\"\x27][^>]*>\s*([^\n<]+)", content, re.I) or
                                    re.search(r"class=[\"\x27][^\"\x27]*(?:signal-score|sb-score-badge|score-badge)[^\"\x27]*[\"\x27][^>]*>([^<]+)", content, re.I) or
                                    re.search(r"综合评分[^\n\d<]*[:：║\s]*([\d\.]+)\s*/\s*10", content, re.I) or
                                    re.search(r"综合得分[^\n\d<]*[:：║\s]*([\d\.]+)\s*/\s*10", content, re.I) or
                                    re.search(r"量化评分[^\n\d<]*[:：║\s]*([\d\.]+)\s*/\s*10", content, re.I) or
                                    re.search(r"SCORE:\s*([\d\.]+\s*/\s*10)", content, re.I) or
                                    re.search(r"Score:\s*([\d\.]+)\s*/\s*10", content, re.I) or
                                    re.search(r"Composite:\s*([\d\.]+)\s*/\s*10", content, re.I) or
                                    re.search(r"加权综合量化总分[^\n<]*</td>\s*<td[^>]*>\s*<strong>\s*([\d\.]+)", content, re.I)
                                )
                                if score_m:
                                    raw_s = score_m.group(1).replace('SCORE:', '').replace('Score:', '').strip()
                                    num_m = re.search(r'([\d\.]+)', raw_s)
                                    if num_m:
                                        score = float(num_m.group(1))

                            # 3. Verdict regex patterns
                            if not verdict:
                                verdict_m = (
                                    re.search(r"(?:hero-meta-label|signal-lbl|signal-item-label|sb-item-label|hero-kpi-lbl)[^>]*>\s*(?:核心信号|综合评级|投资评级|投资结论|投资信号|评级|加权评级|Signal|Verdict)[^<]*</(?:span|div)>\s*<(?:span|div)[^>]*class=[\"\x27][^\"\x27]*(?:hero-meta-value|signal-val|signal-item-val|sb-item-val|hero-kpi-val|hero-kpi-sub)[^\"\x27]*[\"\x27][^>]*>([^<]+)</(?:span|div)>", content, re.I) or
                                    re.search(r"hero-kpi-sub[^>]*>\s*加权评级[：:\s]*([^<]+)", content, re.I) or
                                    re.search(r"INVESTMENT SIGNAL & VERDICT[\s\S]*?<h2[^>]*>([^<]+)</h2>", content, re.I) or
                                    re.search(r"class=[\"\x27][^\"\x27]*(?:signal-badge|signal-verdict)[^\"\x27]*[\"\x27][^>]*>([^<]+)", content, re.I) or
                                    re.search(r"signal-verdict[^>]*>([\s\S]*?)</div>", content, re.I) or
                                    re.search(r"投资信号[^\n:]*[:：║\s]*([^\n\r<║]+)", content, re.I) or
                                    re.search(r"投资结论[^\n:]*[:：║\s]*([^\n\r<║]+)", content, re.I)
                                )
                                if verdict_m:
                                    verdict = re.sub(r'<[^>]+>', '', verdict_m.group(1)).strip().rstrip("║").strip()
                                    verdict = re.sub(r'^(?:加权评级|投资评级|核心信号|投资结论|投资信号)[：:\s]*', '', verdict)

                            # 4. Action regex patterns
                            if not action:
                                action_m = (
                                    re.search(r"(?:signal-lbl|sig-label|sb-item-label)[^>]*>\s*(?:建议操作|操作建议|行动指引|Action)[^<]*</div>\s*<div[^>]*class=[\"\x27][^\"\x27]*(?:signal-val|sig-val|sb-item-val)[^\"\x27]*[\"\x27][^>]*>([^<]+)</div>", content, re.I) or
                                    re.search(r"行动指引[^\n:]*[:：║\s]*([^\n\r<║]+)", content, re.I) or
                                    re.search(r"操作建议[^\n:]*[:：║\s]*([^\n\r<║]+)", content, re.I) or
                                    re.search(r"class=[\"\x27][^\"\x27]*(?:sig-action|signal-action)[^\"\x27]*[\"\x27][^>]*>([^<]+)", content, re.I)
                                )
                                if action_m:
                                    action = re.sub(r'<[^>]+>', '', action_m.group(1)).strip().rstrip("║").strip()

                            # 5. Summary regex patterns
                            sum_m = (
                                re.search(r"<strong>核心投资逻辑[：:]*</strong>([\s\S]*?)</p>", content, re.I) or
                                re.search(r"<strong>核心投资论点[：:]*</strong>([\s\S]*?)</p>", content, re.I) or
                                re.search(r"<strong>核心投资主线[：:]*</strong>([\s\S]*?)(?:</div>|</p>)", content, re.I) or
                                re.search(r"class=[\"\x27][^\"\x27]*signal-main[^\"\x27]*[\"\x27][\s\S]*?<div[^>]*style=[\"\x27][^\"\x27]*max-width:\s*800px[^\"\x27]*[\"\x27][^>]*>([\s\S]*?)</div>", content, re.I) or
                                re.search(r"class=[\"\x27][^\"\x27]*signal-card[^\"\x27]*[\"\x27][\s\S]*?<p[^>]*>([\s\S]*?)</p>", content, re.I)
                            )
                            if sum_m:
                                summary = re.sub(r'<[^>]+>', '', sum_m.group(1)).strip()
                    except Exception:
                        pass

                    disk_cache[f] = {
                        "mtime": mtime,
                        "score": score,
                        "verdict": verdict,
                        "action": action,
                        "summary": summary
                    }
                    cache_updated = True

                if clean_t not in reports or date_str > reports[clean_t]["date"]:
                    file_uri = f"file://{filepath}"
                    try:
                        rel_path = os.path.relpath(filepath, BASE_DIR)
                    except Exception:
                        rel_path = file_uri
                    reports[clean_t] = {
                        "file": f,
                        "file_path": filepath,
                        "file_url": file_uri,
                        "rel_path": rel_path,
                        "date": date_str,
                        "age_days": age_days,
                        "is_stale": is_stale,
                        "score": score,
                        "verdict": verdict,
                        "action": action,
                        "summary": summary,
                        "raw_ticker": raw_t,
                    }

        if cache_updated:
            atomic_write_json(cache_file, disk_cache)

    except Exception as e:
        logger.warning(f"Error scanning InvestSkill output directory: {e}")

    return reports
